version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - intra
    restart: always

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind

  db:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/database
      o: bind

networks:
  intra:
    driver: bridge
